name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - runtime: win-x64
            os: windows
          - runtime: linux-x64
            os: linux
          - runtime: osx-x64
            os: osx

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/FrxEdit.Cli/FrxEdit.Cli.csproj
      
    - name: Build and Publish
      run: dotnet publish src/FrxEdit.Cli/FrxEdit.Cli.csproj -c Release -r ${{ matrix.runtime }} --self-contained true -p:PublishSingleFile=true -o ./publish/${{ matrix.runtime }}
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: frxedit-${{ matrix.os }}
        path: ./publish/${{ matrix.runtime }}/*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        
      - name: Zip binaries
        run: |
          zip -j frxedit-windows.zip frxedit-windows/*
          zip -j frxedit-linux.zip frxedit-linux/*
          zip -j frxedit-osx.zip frxedit-osx/*
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            frxedit-windows.zip
            frxedit-linux.zip
            frxedit-osx.zip
          generate_release_notes: true
