name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - runtime: win-x64
            os: windows
          - runtime: linux-x64
            os: linux
          - runtime: osx-x64
            os: osx

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/FrxEdit.Cli/FrxEdit.Cli.csproj
      
    - name: Build Framework-Dependent
      run: dotnet publish src/FrxEdit.Cli/FrxEdit.Cli.csproj -c Release -r ${{ matrix.runtime }} --self-contained false -p:PublishSingleFile=true -o ./publish/dependent/${{ matrix.runtime }}

    - name: Build Standalone
      run: dotnet publish src/FrxEdit.Cli/FrxEdit.Cli.csproj -c Release -r ${{ matrix.runtime }} --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -o ./publish/standalone/${{ matrix.runtime }}
      
    - name: Upload Artifact Dependent
      uses: actions/upload-artifact@v4
      with:
        name: frxedit-${{ matrix.os }}-framework-dependent
        path: ./publish/dependent/${{ matrix.runtime }}/*

    - name: Upload Artifact Standalone
      uses: actions/upload-artifact@v4
      with:
        name: frxedit-${{ matrix.os }}-standalone
        path: ./publish/standalone/${{ matrix.runtime }}/*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        
      - name: Zip binaries
        run: |
          zip -j frxedit-windows-framework-dependent.zip frxedit-windows-framework-dependent/*
          zip -j frxedit-windows-standalone.zip frxedit-windows-standalone/*
          zip -j frxedit-linux-framework-dependent.zip frxedit-linux-framework-dependent/*
          zip -j frxedit-linux-standalone.zip frxedit-linux-standalone/*
          zip -j frxedit-osx-framework-dependent.zip frxedit-osx-framework-dependent/*
          zip -j frxedit-osx-standalone.zip frxedit-osx-standalone/*
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            frxedit-*-framework-dependent.zip
            frxedit-*-standalone.zip
          generate_release_notes: true
